version: '3.4'

services:
  skillsapi:
    image: skillsapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_skillsapi$
    volumes:
      - G:\Classes\modenWebStack\00 SkillsApi\SkillsApi\SkillsApi:/app
      - C:\Users\Alexander\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_skillsapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_skillsapi$ \"bin/Debug/netcoreapp2.1/SkillsApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
